### ISSUE TITLE
Error plotting trajectory generated by heliopy.spice

### ISSUE THREAD

**Issue by AeroEngS** [heliopython/heliopy#914]
import heliopy.data.spice as spicedata
import heliopy.spice as spice
from datetime import datetime, timedelta
import astropy.units as u
import numpy as np
import matplotlib.pyplot as plt

kernels = spicedata.get_kernel('psp')
kernels += spicedata.get_kernel('psp_pred')
spice.furnish(kernels)
psp = spice.Trajectory('SPP')

starttime = datetime(2019,8,26,0,0,11,843)
endtime = starttime + timedelta(days=1)
times = []
while starttime < endtime:
    times.append(starttime)
    starttime += timedelta(seconds=13)
    
psp.generate_positions(times, 'Sun', 'ECLIPJ2000')

plt.plot(psp.times,psp.r)

I get the following error when I try to plot PSP data for the given time range:

TypeError: float() argument must be a string or a number, not 'Time'
ValueError: setting an array element with a sequence.

**Comment by dstansby** [comment]
Could you post the full error message with line numbers? I suspect you need to import astropy.time here to register the correct plotting converters, but I'm not sure.

**Comment by AeroEngS** [comment]
TypeError: float() argument must be a string or a number, not 'Time'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "<ipython-input-28-c7bf9af2d67a>", line 1, in <module>
    plt.plot(psp.times, psp.r)

  File "C:\Users\joela\anaconda3\lib\site-packages\matplotlib\pyplot.py", line 2796, in plot
    is not None else {}), **kwargs)

  File "C:\Users\joela\anaconda3\lib\site-packages\matplotlib\axes\_axes.py", line 1667, in plot
    self.add_line(line)

  File "C:\Users\joela\anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 1902, in add_line
    self._update_line_limits(line)

  File "C:\Users\joela\anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 1924, in _update_line_limits
    path = line.get_path()

  File "C:\Users\joela\anaconda3\lib\site-packages\matplotlib\lines.py", line 1027, in get_path
    self.recache()

  File "C:\Users\joela\anaconda3\lib\site-packages\matplotlib\lines.py", line 670, in recache
    x = _to_unmasked_float_array(xconv).ravel()

  File "C:\Users\joela\anaconda3\lib\site-packages\matplotlib\cbook\__init__.py", line 1388, in _to_unmasked_float_array
    return np.ma.asarray(x, float).filled(np.nan)

  File "C:\Users\joela\anaconda3\lib\site-packages\numpy\ma\core.py", line 7849, in asarray
    subok=False, order=order)

  File "C:\Users\joela\anaconda3\lib\site-packages\numpy\ma\core.py", line 2795, in __new__
    order=order, subok=True, ndmin=ndmin)

ValueError: setting an array element with a sequence.

**Comment by dstansby** [comment]
It looks like matplotlib doesn't like plotting `astropy.time.Time` objects. I think you have to manually enable time plotting support in astropy, see https://docs.astropy.org/en/stable/visualization/matplotlib_integration.html#plotting-times. Since this doesn't seem to be a heliopy specific bug I'm going to close, but I'll open a new issue to make sure heliopy automatically sets up time plotting support in future.
